### ISSUE TITLE
[FEAT] 입력 시스템

### ISSUE THREAD

**Issue by evryhungry** [dtd1232/2024-1-Sirius-Project#10]
## Issue

- 현재로서는 자동으로 입력 창이 선택이 된 상태이며, 엔터 입력시 입력 창이 비워지고, 입력한 내용이 저장되는 시스템만 구현.

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] : 게임 시작 시 자동 입력 창 선택.
- [x] : Enter 입력 시 입력 창  clear.
- [x] : Enter 입력 시 입력한 내용 string 저장.
