### ISSUE TITLE
[FEAT] 플레이어 이동 시스템과 장애물 자동 회피 시스템

### ISSUE THREAD

**Issue by YoonHaJun1** [dtd1232/2024-1-Sirius-Project#12]
## Issue

- 플레이어 이동 시스템
- 장애물 자동 회피 시스템

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 플레이어 이동 시스템 구현
- [x] 플레이어 점프 구현
- [x] 장애물 자동회피 구현
