### ISSUE TITLE
[FEAT] 비정상적 입력 방지 시스템

### ISSUE THREAD

**Issue by dtd1232** [dtd1232/2024-1-Sirius-Project#16]
## Issue

- 게임 내에서 복사/붙여넣기를 막는 시스템 개발
- 도현이가 만든 입력 씬에서 작업할 예정

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [ ] 입력창 및 경고창 위치 조정
- [ ] Ctrl + c, v 입력시 경고
  - [x] Ctrl + c, v 입력 감지
  - [x] 입력시 경고 이벤트 발생
