### ISSUE TITLE
[FEAT] 선택지 시스템 추가

### ISSUE THREAD

**Issue by khlee8688** [dtd1232/2024-1-Sirius-Project#2]
## Issue

- 선택지(UI) 클릭 시 Debug.Log 통해 출력

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [ ] 선택지 UI
- [ ] 선택한 항목을 불러오기
- [ ] “선택한 항목”을 console에 출력
- [ ] class와 enum 차이 확인
