### ISSUE TITLE
[FEAT] 플레이어 자동 이동과 입력에 따른 행동 변화

### ISSUE THREAD

**Issue by YoonHaJun1** [dtd1232/2024-1-Sirius-Project#20]
## Issue

- 게임을 시작하면 아무 입력이 없는 상태로 시작
   입력시 다음 장애물을 만나면 그 행동을 함
   행동을 하다가 부딫히면 사망 (Slide류에 점프를 하면 부딪히고 사망)
   올바른 행동시 정상적으로 회피
   한번 회피 이후 플레이어의 다음 행동이 리셋되도록 변경

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 아무 입력이 없는 상태로 시작
- [x] 입력 시 다음 장애물을 만나면 행동
- [x] 행동을 하다 부딪히면 사망
- [x] 올바른 행동 시 정상적으로 회피
- [x] 한 번 회피 이후 플레이어 행동 초기화
