### ISSUE TITLE
[FEAT] Keyboard 입력으로 인한 Scene 이동

### ISSUE THREAD

**Issue by evryhungry** [dtd1232/2024-1-Sirius-Project#24]
## Issue
1. 메인화면에서 옵션창을 띄우기 (임시로 창 만들기만 하면 됨)
2. 옵션창에서 메인화면으로 이동
3. 메인화면에서 게임씬으로 이동
3-1. 메인화면 > 캐릭터 선택 > 게임씬 으로 이동 예정
모든 입력은 입력창의 입력을 통해서 이동
자세한 내용은 기획에 추가 서술 할 예정

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 옵션 창 띄우기
- [x] 옵션 창에서 메인 Scene으로 이동
- [x] 메인 창에서 게임 Scene으로 이동  
- [x] 모든 이동은 keyboard 입력으로 처리.
