### ISSUE TITLE
[FEAT] 현재 입력 / 사용 가능한 플레이어 행동 전체 UI로 표기

### ISSUE THREAD

**Issue by AdHoc2675** [dtd1232/2024-1-Sirius-Project#26]
## Issue

- 현재 입력 / 사용 가능한 플레이어 행동 전체 UI로 표기

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 게임 진행 중 만났던 (해결했던) 장애물 판별
- [x] 해당 장애물의 키워드 기억
- [x] 최종적으로 표시할 데이터는 장애물 - 키워드 쌍
- [x] 키워드 - 장애물 판별 쌍을 왼쪽 하단에 표기
