### ISSUE TITLE
[FEAT] 플레이어 이동 시스템과 장애물 자동 회피 시스템

### ISSUE THREAD

**Issue by YoonHaJun1** [dtd1232/2024-1-Sirius-Project#3]
## Issue

- client에서 POST 요청이 들어왔어요

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [ ] 배경 움직임 구현
  - [ ] 현재 화면이 움직이고 난 뒤 다른 배경화면이 나오게 하기
  - [ ] 배경화면이 다 나오면 처음 화면으로 되돌아가기
- [ ] 플레이어 점프 구현
  - [ ] 장애물을 만났을 때 플레이어가 가지고 있는 jump스트링과 비교하여 점프하도록 하기
