### ISSUE TITLE
[FEAT] 스테이지 구성

### ISSUE THREAD

**Issue by khlee8688** [dtd1232/2024-1-Sirius-Project#31]
## Issue

- 약 2분동안만 플레이가 진행하며, 진행 중에 죽으면 게임오버를 n초 동안 보여주고 메인화면으로 다시이동

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 상단에 progression bar (linear timer)
- [x] game over (n초 동안) 띄우기
- [x] button (to main menu) 추가
