### ISSUE TITLE
[FEAT] 선택지 시스템 추가

### ISSUE THREAD

**Issue by khlee8688** [dtd1232/2024-1-Sirius-Project#6]
## Issue

- 선택지(UI) 클릭 시 Debug.Log/print 통해 출력

## ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## To-do
- [x] 선택지 UI 대략적 구현
- [x] 선택한 항목을 불러오기
- [x] “선택한 항목”을 console에 출력 (Debug.Log/print)
- [x] class, enum 차이 확인
   - [x] class
   - [x] enum
